export const CHARACTERS = Object.freeze([
  'images/characters/character-1.png',
  'images/characters/character-2.png',
  'images/characters/character-3.png',
  'images/characters/character-4.png',
  'images/characters/character-5.png',
  'images/characters/character-6.png',
]);

export const SERVICES = Object.freeze([
  {
    heading : 'Thousands of unique NFTs',
    description : 'Each character is entirely unique and is generated by combining attributes such as colour palettes, skin tones, facial traits, outfits and accessories. With nearly endless combinations, all characters are guaranteed to be one of a kind.'
  },
  {
    heading : 'Secure the most rare',
    description : 'Even though no two Tinyfaces will ever be the same, some variations are rarer than others. Watch out for special accessories and raw materials - the rarer the attributes, the rarer your character will be.'
  },
  {
    heading : 'Our environmental impact matters to us.',
    description : 'Even though no two Tinyfaces will ever be the same, some variations are rarer than others. Watch out for special accessories and raw materials - the rarer the attributes, the rarer your character will be.'
  },
])